### PR TITLE
TEP004: tardisatomic improvement

### PR DESCRIPTION
**Pull request by wkerzendorf**
This is the TEP for the tardis atomic improvement. @lukeshingles we should iterate on this.

### CODE REVIEW

**Comment by unoebauer** [comment]
A very important task - the TEP needs polishing but if we are in a hurry, I am fine with merging this one now.

**Comment by unoebauer** [comment]
concerning GSoC, this seems to be a tough nut to crack...but I guess any progress on this helps

**Comment by wkerzendorf** [comment]
@lukeshingles so I implemented the changes.

**Comment by wkerzendorf** [comment]
@unoebauer We're focusing on the data parsing for GSoC and @lukeshingles and myself will migrate this to the database.

**Pull request merged**
