### PR TITLE
added TEP1

### PR DESCRIPTION
**Pull request by wkerzendorf**
- TEP1.rst: added the TEP1 proposal

### CODE REVIEW

**Comment by wkerzendorf** [comment]
@unoebauer @orbitfold a first example

**Comment by unoebauer** [comment]
Sounds very reasonable to me

**Comment by wkerzendorf** [comment]
@unoebauer should we merge this - I want to link GSoC to this. We can always amend it later.

**Comment by wkerzendorf** [comment]
@orbitfold?

**Comment by orbitfold** [comment]
Sure, we can merge this.

**Comment by unoebauer** [comment]
Yes, let's merge

**Pull request merged**
