### PR TITLE
TEP 005: Formal Integral Method for Downbranching Scheme

### PR DESCRIPTION
**Pull request by unoebauer**
This TEP suggests to implement the formal integral approach of Lucy 1999 to get a noise-free spectrum for Tardis calculations in which the downbranching line interaction treatment is used.

### CODE REVIEW

**Comment by unoebauer** [comment]
@wkerzendorf, @ssim, @orbitfold, @chvogl : Opinions, suggestions?

**Comment by chvogl** [comment]
@unoebauer there is a small error in the text:

> Thus, devising and implementing algorithms to improve the signal-to-noise ratio are crucial a curcial part of the Tardis development process.

**Comment by wkerzendorf** [comment]
@unoebauer looks good to me - I would merge and then amend the TEP when necessary.

**Comment by unoebauer** [comment]
Fixed the typo. @wkerzendorf merge at will

**Pull request merged**
